// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('DescriptionText', { text: 'Description' });
    CreateText('AmountText', { text: 'Amount' });
    CreateGlassButton('submitButton', { onclick: 'submit_Click', text: 'add transaction' });
    CreateText('text', { text: 'Username' });
    CreateText('text1', { text: 'Password' });
    CreateIndicator('latestStatusIndicator', { onValue: 1, criticalValue: 15, warningValue: 10 });
    CreateText('text2', { text: 'Selected Account' });
    CreateText('text3', { text: 'Tags' });
    CreateText('statusText', { text: 'status text' });
    CreateText('text4', { text: 'Add a transaction to buxfer' });
}
window.addEventListener('load', setupParts, false);
